#!/bin/sh
# 
# 	${project trunk_name} - ${project trunk_description}
#	Version: ${Version}
# 	Copyright (C) ${date %Y} ${user name}.  All rights reserved.
# 	Written by ${user email}
# 
# 	Redistribution and use in source and binary forms, with or without
# 	modification, are permitted provided that the following conditions are
# 	met:
# 	
# 	 1. Redistributions of source code must retain the above copyright
# 	 notice, this list of conditions and the following disclaimer.
# 	
# 	 2. Redistributions in binary form must reproduce the above copyright
# 	 notice, this list of conditions and the following disclaimer in the
# 	 documentation and/or other materials provided with the distribution.
# 	
# 	THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# 	IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# 	DISCLAIMED. IN NO EVENT SHALL THE AUTHER OR CONTRIBUTORS BE LIABLE FOR
# 	ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# 	DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# 	OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# 	HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# 	STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# 	ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# 	POSSIBILITY OF SUCH DAMAGE.
#
# Test of the ??? functionality
#
work=$${TMPDIR:-/tmp}/$$$$
PAGER=cat
export PAGER
umask 022
here=`pwd`
if test $$? -ne 0 ; then exit 2; fi
SHELL=/bin/sh
export SHELL

bin="$$here/$${1-.}/bin"

pass()
{
	set +x
	cd $$here
	rm -rf $$work
	exit 0
}
fail()
{
	set +x
	echo 'FAILED test of the ??? functionality' 1>&2
	cd $$here
	rm -rf $$work
	exit 1
}
no_result()
{
	set +x
	echo 'NO RESULT for test of the ??? functionality' 1>&2
	cd $$here
	rm -rf $$work
	exit 2
}
trap \"no_result\" 1 2 3 15

mkdir $$work $$work/lib
if test $$? -ne 0 ; then no_result; fi

#####
# Copy accessory files.
#####
cp `echo $$0 | sed 's/\.sh//'`* $$work

if test $$? -ne 0 ; then no_result; fi

cd $$work
if test $$? -ne 0 ; then no_result; fi

#
# test the ??? functionality
#

$$bin/progA
if test $$? -ne 0 ; then fail; fi

#
# Only definite negatives are possible.
# The functionality exercised by this test appears to work,
# no other guarantees are made.
#
pass
